# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ali/Oreon-system-manager

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ali/Oreon-system-manager

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ali/Oreon-system-manager/CMakeFiles /home/ali/Oreon-system-manager//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ali/Oreon-system-manager/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named oreon-system-manager

# Build rule for target.
oreon-system-manager: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 oreon-system-manager
.PHONY : oreon-system-manager

# fast build rule for target.
oreon-system-manager/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oreon-system-manager.dir/build.make CMakeFiles/oreon-system-manager.dir/build
.PHONY : oreon-system-manager/fast

#=============================================================================
# Target rules for targets named oreon-system-manager_autogen

# Build rule for target.
oreon-system-manager_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 oreon-system-manager_autogen
.PHONY : oreon-system-manager_autogen

# fast build rule for target.
oreon-system-manager_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oreon-system-manager_autogen.dir/build.make CMakeFiles/oreon-system-manager_autogen.dir/build
.PHONY : oreon-system-manager_autogen/fast

oreon-system-manager_autogen/mocs_compilation.o: oreon-system-manager_autogen/mocs_compilation.cpp.o
.PHONY : oreon-system-manager_autogen/mocs_compilation.o

# target to build an object file
oreon-system-manager_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oreon-system-manager.dir/build.make CMakeFiles/oreon-system-manager.dir/oreon-system-manager_autogen/mocs_compilation.cpp.o
.PHONY : oreon-system-manager_autogen/mocs_compilation.cpp.o

oreon-system-manager_autogen/mocs_compilation.i: oreon-system-manager_autogen/mocs_compilation.cpp.i
.PHONY : oreon-system-manager_autogen/mocs_compilation.i

# target to preprocess a source file
oreon-system-manager_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oreon-system-manager.dir/build.make CMakeFiles/oreon-system-manager.dir/oreon-system-manager_autogen/mocs_compilation.cpp.i
.PHONY : oreon-system-manager_autogen/mocs_compilation.cpp.i

oreon-system-manager_autogen/mocs_compilation.s: oreon-system-manager_autogen/mocs_compilation.cpp.s
.PHONY : oreon-system-manager_autogen/mocs_compilation.s

# target to generate assembly for a file
oreon-system-manager_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oreon-system-manager.dir/build.make CMakeFiles/oreon-system-manager.dir/oreon-system-manager_autogen/mocs_compilation.cpp.s
.PHONY : oreon-system-manager_autogen/mocs_compilation.cpp.s

qrc_resources.o: qrc_resources.cpp.o
.PHONY : qrc_resources.o

# target to build an object file
qrc_resources.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oreon-system-manager.dir/build.make CMakeFiles/oreon-system-manager.dir/qrc_resources.cpp.o
.PHONY : qrc_resources.cpp.o

qrc_resources.i: qrc_resources.cpp.i
.PHONY : qrc_resources.i

# target to preprocess a source file
qrc_resources.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oreon-system-manager.dir/build.make CMakeFiles/oreon-system-manager.dir/qrc_resources.cpp.i
.PHONY : qrc_resources.cpp.i

qrc_resources.s: qrc_resources.cpp.s
.PHONY : qrc_resources.s

# target to generate assembly for a file
qrc_resources.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oreon-system-manager.dir/build.make CMakeFiles/oreon-system-manager.dir/qrc_resources.cpp.s
.PHONY : qrc_resources.cpp.s

src/audiomanager.o: src/audiomanager.cpp.o
.PHONY : src/audiomanager.o

# target to build an object file
src/audiomanager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oreon-system-manager.dir/build.make CMakeFiles/oreon-system-manager.dir/src/audiomanager.cpp.o
.PHONY : src/audiomanager.cpp.o

src/audiomanager.i: src/audiomanager.cpp.i
.PHONY : src/audiomanager.i

# target to preprocess a source file
src/audiomanager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oreon-system-manager.dir/build.make CMakeFiles/oreon-system-manager.dir/src/audiomanager.cpp.i
.PHONY : src/audiomanager.cpp.i

src/audiomanager.s: src/audiomanager.cpp.s
.PHONY : src/audiomanager.s

# target to generate assembly for a file
src/audiomanager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oreon-system-manager.dir/build.make CMakeFiles/oreon-system-manager.dir/src/audiomanager.cpp.s
.PHONY : src/audiomanager.cpp.s

src/containermanager.o: src/containermanager.cpp.o
.PHONY : src/containermanager.o

# target to build an object file
src/containermanager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oreon-system-manager.dir/build.make CMakeFiles/oreon-system-manager.dir/src/containermanager.cpp.o
.PHONY : src/containermanager.cpp.o

src/containermanager.i: src/containermanager.cpp.i
.PHONY : src/containermanager.i

# target to preprocess a source file
src/containermanager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oreon-system-manager.dir/build.make CMakeFiles/oreon-system-manager.dir/src/containermanager.cpp.i
.PHONY : src/containermanager.cpp.i

src/containermanager.s: src/containermanager.cpp.s
.PHONY : src/containermanager.s

# target to generate assembly for a file
src/containermanager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oreon-system-manager.dir/build.make CMakeFiles/oreon-system-manager.dir/src/containermanager.cpp.s
.PHONY : src/containermanager.cpp.s

src/drivermanager.o: src/drivermanager.cpp.o
.PHONY : src/drivermanager.o

# target to build an object file
src/drivermanager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oreon-system-manager.dir/build.make CMakeFiles/oreon-system-manager.dir/src/drivermanager.cpp.o
.PHONY : src/drivermanager.cpp.o

src/drivermanager.i: src/drivermanager.cpp.i
.PHONY : src/drivermanager.i

# target to preprocess a source file
src/drivermanager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oreon-system-manager.dir/build.make CMakeFiles/oreon-system-manager.dir/src/drivermanager.cpp.i
.PHONY : src/drivermanager.cpp.i

src/drivermanager.s: src/drivermanager.cpp.s
.PHONY : src/drivermanager.s

# target to generate assembly for a file
src/drivermanager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oreon-system-manager.dir/build.make CMakeFiles/oreon-system-manager.dir/src/drivermanager.cpp.s
.PHONY : src/drivermanager.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oreon-system-manager.dir/build.make CMakeFiles/oreon-system-manager.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oreon-system-manager.dir/build.make CMakeFiles/oreon-system-manager.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oreon-system-manager.dir/build.make CMakeFiles/oreon-system-manager.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/mainwindow.o: src/mainwindow.cpp.o
.PHONY : src/mainwindow.o

# target to build an object file
src/mainwindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oreon-system-manager.dir/build.make CMakeFiles/oreon-system-manager.dir/src/mainwindow.cpp.o
.PHONY : src/mainwindow.cpp.o

src/mainwindow.i: src/mainwindow.cpp.i
.PHONY : src/mainwindow.i

# target to preprocess a source file
src/mainwindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oreon-system-manager.dir/build.make CMakeFiles/oreon-system-manager.dir/src/mainwindow.cpp.i
.PHONY : src/mainwindow.cpp.i

src/mainwindow.s: src/mainwindow.cpp.s
.PHONY : src/mainwindow.s

# target to generate assembly for a file
src/mainwindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oreon-system-manager.dir/build.make CMakeFiles/oreon-system-manager.dir/src/mainwindow.cpp.s
.PHONY : src/mainwindow.cpp.s

src/packagemanager.o: src/packagemanager.cpp.o
.PHONY : src/packagemanager.o

# target to build an object file
src/packagemanager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oreon-system-manager.dir/build.make CMakeFiles/oreon-system-manager.dir/src/packagemanager.cpp.o
.PHONY : src/packagemanager.cpp.o

src/packagemanager.i: src/packagemanager.cpp.i
.PHONY : src/packagemanager.i

# target to preprocess a source file
src/packagemanager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oreon-system-manager.dir/build.make CMakeFiles/oreon-system-manager.dir/src/packagemanager.cpp.i
.PHONY : src/packagemanager.cpp.i

src/packagemanager.s: src/packagemanager.cpp.s
.PHONY : src/packagemanager.s

# target to generate assembly for a file
src/packagemanager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oreon-system-manager.dir/build.make CMakeFiles/oreon-system-manager.dir/src/packagemanager.cpp.s
.PHONY : src/packagemanager.cpp.s

src/privilegedexecutor.o: src/privilegedexecutor.cpp.o
.PHONY : src/privilegedexecutor.o

# target to build an object file
src/privilegedexecutor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oreon-system-manager.dir/build.make CMakeFiles/oreon-system-manager.dir/src/privilegedexecutor.cpp.o
.PHONY : src/privilegedexecutor.cpp.o

src/privilegedexecutor.i: src/privilegedexecutor.cpp.i
.PHONY : src/privilegedexecutor.i

# target to preprocess a source file
src/privilegedexecutor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oreon-system-manager.dir/build.make CMakeFiles/oreon-system-manager.dir/src/privilegedexecutor.cpp.i
.PHONY : src/privilegedexecutor.cpp.i

src/privilegedexecutor.s: src/privilegedexecutor.cpp.s
.PHONY : src/privilegedexecutor.s

# target to generate assembly for a file
src/privilegedexecutor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oreon-system-manager.dir/build.make CMakeFiles/oreon-system-manager.dir/src/privilegedexecutor.cpp.s
.PHONY : src/privilegedexecutor.cpp.s

src/repositorymanager.o: src/repositorymanager.cpp.o
.PHONY : src/repositorymanager.o

# target to build an object file
src/repositorymanager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oreon-system-manager.dir/build.make CMakeFiles/oreon-system-manager.dir/src/repositorymanager.cpp.o
.PHONY : src/repositorymanager.cpp.o

src/repositorymanager.i: src/repositorymanager.cpp.i
.PHONY : src/repositorymanager.i

# target to preprocess a source file
src/repositorymanager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oreon-system-manager.dir/build.make CMakeFiles/oreon-system-manager.dir/src/repositorymanager.cpp.i
.PHONY : src/repositorymanager.cpp.i

src/repositorymanager.s: src/repositorymanager.cpp.s
.PHONY : src/repositorymanager.s

# target to generate assembly for a file
src/repositorymanager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oreon-system-manager.dir/build.make CMakeFiles/oreon-system-manager.dir/src/repositorymanager.cpp.s
.PHONY : src/repositorymanager.cpp.s

src/systemutils.o: src/systemutils.cpp.o
.PHONY : src/systemutils.o

# target to build an object file
src/systemutils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oreon-system-manager.dir/build.make CMakeFiles/oreon-system-manager.dir/src/systemutils.cpp.o
.PHONY : src/systemutils.cpp.o

src/systemutils.i: src/systemutils.cpp.i
.PHONY : src/systemutils.i

# target to preprocess a source file
src/systemutils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oreon-system-manager.dir/build.make CMakeFiles/oreon-system-manager.dir/src/systemutils.cpp.i
.PHONY : src/systemutils.cpp.i

src/systemutils.s: src/systemutils.cpp.s
.PHONY : src/systemutils.s

# target to generate assembly for a file
src/systemutils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oreon-system-manager.dir/build.make CMakeFiles/oreon-system-manager.dir/src/systemutils.cpp.s
.PHONY : src/systemutils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... oreon-system-manager_autogen"
	@echo "... oreon-system-manager"
	@echo "... oreon-system-manager_autogen/mocs_compilation.o"
	@echo "... oreon-system-manager_autogen/mocs_compilation.i"
	@echo "... oreon-system-manager_autogen/mocs_compilation.s"
	@echo "... qrc_resources.o"
	@echo "... qrc_resources.i"
	@echo "... qrc_resources.s"
	@echo "... src/audiomanager.o"
	@echo "... src/audiomanager.i"
	@echo "... src/audiomanager.s"
	@echo "... src/containermanager.o"
	@echo "... src/containermanager.i"
	@echo "... src/containermanager.s"
	@echo "... src/drivermanager.o"
	@echo "... src/drivermanager.i"
	@echo "... src/drivermanager.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/mainwindow.o"
	@echo "... src/mainwindow.i"
	@echo "... src/mainwindow.s"
	@echo "... src/packagemanager.o"
	@echo "... src/packagemanager.i"
	@echo "... src/packagemanager.s"
	@echo "... src/privilegedexecutor.o"
	@echo "... src/privilegedexecutor.i"
	@echo "... src/privilegedexecutor.s"
	@echo "... src/repositorymanager.o"
	@echo "... src/repositorymanager.i"
	@echo "... src/repositorymanager.s"
	@echo "... src/systemutils.o"
	@echo "... src/systemutils.i"
	@echo "... src/systemutils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

